# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Manufacturing Data Repository 
tagline:          'A Jekyll theme'
description:      'Made by <a href="https://twitter.com/danaikorre" target="_blank">@dkorre</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Danai Korre'
  url:            https://twitter.com/danaikorre

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
